### ISSUE TITLE
Annotations and area calculation.

### ISSUE THREAD

**Issue by Dave-Dush** [yukkyo/voc2coco#10]
@yukkyo Good attempt, however, the problem with annotations written in the .json have specific problem for all annotations.

1. XMIN and YMIN are always reduced by 1 pixel.
2. XMAX and YMAX are assigned values that cannot be traced to original values.
3. Above issues also cause wrong calculations of area of bboxes.

**Comment by Dave-Dush** [comment]
My bad, the remaining 2 values aren't coordinates, but they are width and height of bbox.

**Comment by engrjav** [comment]
@yukkyo  @Dave-Dush 
I see that   under mentioned gives better area, can you explain why xmin and ymin are subtracted by 1 and also why final area is calculated by subtracted values. When i added 1 in line 70,71  i find better results
o_width = xmax - (xmin+1)   
 o_height = ymax - (ymin+1) # i added +1 here
