### ISSUE TITLE
License and sharing ? =)

### ISSUE THREAD

**Issue by ClemSc** [yukkyo/voc2coco#9]
Hello,

great code yukkyo, thank you ! I would like to use your script in a pipeline that will be released open-source (BSD), and for user convenience, I'd like to provide directly (with all credits to you of course). But I did not find any license disclaimer on your repo. Would you add one ? Otherwise, it is no problem, I will simply instruct users to grab your script here :)

Best,
Clem

**Comment by yukkyo** [comment]
@ClemSc 
Thanks for notifying me!
I choose MIT license, so feel free to use it!
